subjobs_list:
  close:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: Script
    name: "close_ganascia_a1610.urp"
  # move_up:
  #   next_state_if_success: "SUCCESS"
  #   next_state_if_fail: "FAIL"
  #   type: RelativeMove
  #   frame: table
  #   traZmm: 150
  #   linear_velocity_mm_s: 50

initial_state: close
