subjobs_list:
  mount:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: Script
    name: "mount_a1652_dx.urp"
  # close_gripper:
  #   next_state_if_success: "move_down_1"
  #   next_state_if_fail: "FAIL"
  #   type: Gripper
  #   position: 0
  #   force: 100
  #   velocity: 100
  #
  # move_down_1:
  #   next_state_if_success: "move_y_neg"
  #   next_state_if_fail: "FAIL"
  #   type: RelativeMove
  #   frame: table
  #   traZmm: -120
  #   linear_velocity_mm_s: 35
  #
  # move_y_neg:
  #   next_state_if_success: "push_y"
  #   next_state_if_fail: "FAIL"
  #   type: RelativeMove
  #   frame: table
  #   traYmm: -13
  #   linear_velocity_mm_s: 10
  #
  # # spingo per avere il riscontro
  # push_y:
  #     next_state_if_success: "open_gripper"
  #     next_state_if_fail: "FAIL"
  #     type: Touch
  #     goal_twist: [0.000,-0.001,0,0,0,0]
  #     goal_twist_frame: "world"
  #     target_force: 10
  #     relative_target: False
  #     release_condition: "Position"
  #     release_position: 0.0005
  #
  #
  # open_gripper:
  #   next_state_if_success: "detach"
  #   next_state_if_fail: "FAIL"
  #   type: Gripper
  #   position: 15
  #   force: 100
  #   velocity: 100
  #
  # detach:
  #   next_state_if_success: "move_up_1"
  #   next_state_if_fail: "FAIL"
  #   type: Detach
  #
  # move_up_1:
  #   next_state_if_success: "SUCCESS"
  #   next_state_if_fail: "FAIL"
  #   type: RelativeMove
  #   frame: table
  #   traZmm: 120
  #   linear_velocity_mm_s: 35


initial_state: mount
