subjobs_list:
  move_down:
    next_state_if_success: "push_x"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: -131
    linear_velocity_mm_s: 10
  # close_gripper:
  #   next_state_if_success: "push_x"
  #   next_state_if_fail: "FAIL"
  #   type: Gripper
  #   position: 0
  #   force: 100
  #   velocity: 100
  push_x:
    next_state_if_success: "push_z"
    next_state_if_fail: "FAIL"
    type: Touch
    goal_twist: [0.0005,0,0,0,0,0]
    goal_twist_frame: "world"
    target_force: 10
    relative_target: True
    release_condition: "Position"
    release_position: 0.0015
  push_z:
    next_state_if_success: "gripper_50"
    next_state_if_fail: "FAIL"
    type: Touch
    goal_twist: [0,0,-0.0005,0,0,0]
    goal_twist_frame: "world"
    target_force: 3
    relative_target: True
    release_condition: "Position"
    release_position: 0.0005
  gripper_50:
    next_state_if_success: "gripper_50_2"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 50
    force: 100
    velocity: 100
  gripper_50_2:
    next_state_if_success: "push_z_final"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 50
    force: 100
    velocity: 100
  push_z_final:
    next_state_if_success: "move_up"
    next_state_if_fail: "FAIL"
    type: Touch
    goal_twist: [0,0,-0.0015,0,0,0]
    goal_twist_frame: "world"
    target_force: 40
    relative_target: True
    release_condition: "Position"
    release_position: 0.0005
  move_up:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: 130
    linear_velocity_mm_s: 15

initial_state: move_down
