subjobs_list:
  move_in_z:
    next_state_if_success: "move_in_y"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: -136
    linear_velocity_mm_s: 30
  move_in_y:
    next_state_if_success: "push_y"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traYmm: 51
    linear_velocity_mm_s: 10
  push_y:
    next_state_if_success: "move_down"
    next_state_if_fail: "FAIL"
    type: Touch
    goal_twist: [0,0.001,0,0,0,0]
    goal_twist_frame: "world"
    target_force: 7
    relative_target: True
    release_condition: "Position"
    release_position: 0.0005
  move_down:
    next_state_if_success: "gripper_35"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: -2.5
    linear_velocity_mm_s: 5
  # push_z:
  #   next_state_if_success: "gripper_35"
  #   next_state_if_fail: "FAIL"
  #   type: Touch
  #   goal_twist: [0,0,-0.001,0,0,0]
  #   goal_twist_frame: "world"
  #   target_force: 7
  #   relative_target: True
  #   release_condition: "Position"
  #   release_position: 0.0005
  gripper_35:
    next_state_if_success: "move_up"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 35
    force: 100
    velocity: 100
  move_up:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: 120
    linear_velocity_mm_s: 50


initial_state: move_in_z
