subjobs_list:
  move_down:
    next_state_if_success: "seek"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: -200
    linear_velocity_mm_s: 40
  seek:
    next_state_if_success: "push_y"
    next_state_if_fail: "FAIL"
    type: Touch
    goal_twist: [0.0,0,-0.003,0,0,0]
    goal_twist_frame: "world"
    target_force: 20
    relative_target: True
    release_condition: "Position"
    release_position: 0.0002
  push_y:
    next_state_if_success: "push_x"
    next_state_if_fail: "FAIL"
    type: Touch
    goal_twist: [0.0,-0.003,0,0,0,0]
    goal_twist_frame: "world"
    target_force: 60
    relative_target: True
    release_condition: "Position"
    release_position: 0.0001
  push_x:
    next_state_if_success: "push_z"
    next_state_if_fail: "FAIL"
    type: Touch
    goal_twist: [-0.003,0,0.0,0,0,0]
    goal_twist_frame: "world"
    target_force: 20
    relative_target: True
    release_condition: "Position"
    release_position: 0.00001
  push_z:
    next_state_if_success: "gripper_40"
    next_state_if_fail: "FAIL"
    type: Touch
    goal_twist: [0.0,0,-0.003,0,0,0]
    goal_twist_frame: "world"
    target_force: 50
    relative_target: True
    release_condition: "Position"
    release_position: 0.00001
  gripper_40:
    next_state_if_success: "move_up"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 40
    force: 100
    velocity: 100
  move_up:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: 200
    linear_velocity_mm_s: 40

initial_state: move_down
