subjobs_list: #21A1122
  pick_object:
    next_state_if_success: "attach"
    next_state_if_fail: "FAIL"

    type: Script
    name: "pick_a1653.urp"
    # type: Gripper
    # position: 45
    # force: 100
    # velocity: 100
  attach:
    next_state_if_success: "move_up"
    next_state_if_fail: "FAIL"
    type: Attach
  move_up:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: TOOL
    traZmm: -200
    linear_velocity_mm_s: 50
initial_state: pick_object
#
#
# subjobs_list: #21A1122
#   open_gripper:
#     next_state_if_success: "move_down"
#     next_state_if_fail: "FAIL"
#
#     type: Script
#     name: "gripper45.urp"
#     # type: Gripper
#     # position: 45
#     # force: 100
#     # velocity: 100
#   move_down:
#     next_state_if_success: "move_down_2"
#     next_state_if_fail: "FAIL"
#     type: RelativeMove
#     frame: TOOL
#     traZmm: 195
#     linear_velocity_mm_s: 40
#   move_down_2:
#     next_state_if_success: "close_gripper"
#     next_state_if_fail: "FAIL"
#     type: RelativeMove
#     frame: TOOL
#     traZmm: 5
#     linear_velocity_mm_s: 10
#   close_gripper:
#     next_state_if_success: "attach"
#     next_state_if_fail: "FAIL"
#
#     type: Script
#     name: "close_gripper.urp"
#     # type: Gripper
#     # position: 0
#     # force: 100
#     # velocity: 100
#   attach:
#     next_state_if_success: "move_up"
#     next_state_if_fail: "FAIL"
#     type: Attach
#   move_up:
#     next_state_if_success: "SUCCESS"
#     next_state_if_fail: "FAIL"
#     type: RelativeMove
#     frame: TOOL
#     traZmm: -200
#     linear_velocity_mm_s: 50
# initial_state: open_gripper
