subjobs_list:

  open_gripper:
    next_state_if_success: "move_down_1"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 25
    force: 100
    velocity: 100

  move_down_1:
    next_state_if_success: "close_gripper"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: -120
    linear_velocity_mm_s: 35

  close_gripper:
    next_state_if_success: "move_y"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 0
    force: 100
    velocity: 100


  move_y:
    next_state_if_success: "move_up_1"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traYmm: -13
    linear_velocity_mm_s: 10


  move_up_1:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: 120
    linear_velocity_mm_s: 35


initial_state: open_gripper
