fare il check
subjobs_list:
  gripper_35:
    next_state_if_success: "move_down"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 35
    force: 100
    velocity: 100
  move_down:
    next_state_if_success: "close_gripper"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: -120
    linear_velocity_mm_s: 25
  close_gripper:
    next_state_if_success: "move_up"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 0
    force: 100
    velocity: 100
  move_up:
    next_state_if_success: "move_out_y"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: 6
    linear_velocity_mm_s: 25
  move_out_y:
    next_state_if_success: "move_out_z"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traYmm: -55
    linear_velocity_mm_s: 25
  move_out_z:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: 180
    linear_velocity_mm_s: 50

initial_state: gripper_35
