subjobs_list:
  # neutral:
  #   next_state_if_success: "SUCCESS"
  #   next_state_if_fail: "FAIL"
  #   type: RelativeMove
  #   frame: table
  #   traZmm: 0
  #   linear_velocity_mm_s: 0
  unmount_a1653_staffa:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: Script
    name: "unmount_a1653.urp"
  # gripper_50:
  #   next_state_if_success: "move_down"
  #   next_state_if_fail: "FAIL"
  #   type: Gripper
  #   position: 50
  #   force: 100
  #   velocity: 100
  # move_down:
  #   next_state_if_success: "close_gripper"
  #   next_state_if_fail: "FAIL"
  #   type: RelativeMove
  #   frame: table
  #   traZmm: -144
  #   linear_velocity_mm_s: 30
  # close_gripper:
  #   next_state_if_success: "close_gripper_2"
  #   next_state_if_fail: "FAIL"
  #   type: Gripper
  #   position: 0
  #   force: 100
  #   velocity: 100
  # close_gripper_2:
  #   next_state_if_success: "move_up"
  #   next_state_if_fail: "FAIL"
  #   type: Gripper
  #   position: 0
  #   force: 100
  #   velocity: 100
  # move_up:
  #   next_state_if_success: "move_up_2"
  #   next_state_if_fail: "FAIL"
  #   type: RelativeMove
  #   frame: table
  #   traZmm: 4
  #   linear_velocity_mm_s: 2
  #
  # move_up_2:
  #   next_state_if_success: "SUCCESS"
  #   next_state_if_fail: "FAIL"
  #   type: RelativeMove
  #   frame: table
  #   traZmm: 140
  #   linear_velocity_mm_s: 25
initial_state: unmount_a1653_staffa
