subjobs_list:
  move_down:
    next_state_if_success: "move_up"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: -130
    linear_velocity_mm_s: 20
  move_up:
    next_state_if_success: "rot_1"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: 130
    linear_velocity_mm_s: 15
  rot_1:
    next_state_if_success: "rot_2"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    rotZdeg: 90
  rot_2:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    rotZdeg: -90

initial_state: move_down
