
go_to_location_server:

  ik_sol_number: 4
  max_stall_iter: 100
  collision_detector: FCL

  groups:
    manipulator: open_tip

  manipulator:
    preferred_configuration: [1.5707963267949, -2.44346095279206, 2.44346095279206,-1.5707963267949, 1.5707963267949, 0]
    #preferred_configuration: [-1.9769910017596644, -0.8349288266948243, -2.292120933532715, -1.6209961376585902, -1.5518959204303187, 0.5749483108520508]
    preferred_configuration_weight: [1, 1, 1, 1, 1, 1]
    max_ik_goal_number: 32
    use_single_goal: false
    upper_bound: [ 3.14159265358979, -0.122173, 2.75,  3.14,  3.14,  3.14]
    lower_bound: [-3.14159265358979, -3.05,    -2.75, -3.14, -3.14, -3.14]


  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints
