go_to_location:
  - {name: "home",                           frame: "table", position: [-0.228, 0.745, 0.127], quaternion: [0.761, -0.648, -0.033, 0.014]} #only as example
  # - {name: "home3",                          frame: "table", position: [-0.364, 0.420, 0.520], quaternion: [-0.464, -0.462, 0.585, -0.478]} #only as example
  # - {name: "home2",                          frame: "table", position: [0.365, 0.864, 0.522], quaternion: [0.044, 0.653, -0.125, 0.745]} #only as example
  # - {name: "desk1",                          frame: "table", position: [0.454, 0.705, 0.674], quaternion: [0.707, 0.707, -0.026, -0.029]} #to be updated
  # - {name: "warehouse2",                     frame: "table", position: [-0.021, 1.813, 0.535], quaternion: [0.993, -0.112, 0.007, -0.042]} #to be updated
  # - {name: "test_start",                     frame: "table", position: [0.207, 0.467, 0.340], quaternion: [0.927, -0.341, 0.152, 0.037]} #to be updated
  # - {name: "test_stop",                      frame: "table", position: [0.345, 1.594, 0.415], quaternion: [0.878, 0.426, 0.151, -0.155]} #to be updated
  # - {name: "pezzo_cilindrico",               frame: "table", position: [0.302, 0.501, 0.282], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  # - {name: "remove_staffa_pezzo_cilindrico", frame: "table", position: [0.260, 0.502, 0.240], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  # - {name: "insert_staffa_pezzo_cilindrico", frame: "table", position: [0.260, 0.448, 0.305], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  # - {name: "presa_staffa",                   frame: "table", position: [0.001, 0.391, 0.025], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  # - {name: "presa_staffa_up_tmp",            frame: "table", position: [0.001, 0.391, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  # - {name: "cilindro_inbound",               frame: "table", position: [0.071, 0.623, 0.030], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  # - {name: "cilindro_inbound_up_tmp",        frame: "table", position: [0.071, 0.623, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  # - {name: "lavorato_inbound",               frame: "table", position: [0.071, 0.919, 0.030], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  # - {name: "lavorato_inbound_up_tmp",        frame: "table", position: [0.071, 0.919, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  #
  # - {name: "pick_tower_left",                frame: "world", position: [0.299, -0.534, 1.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  # - {name: "place_tower_left",               frame: "world", position: [0.183, -0.506, 1.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]} #to be updated
  #
  # - {name: "pick_object_tower_1",            frame: "world", position: [-0.061, -0.668, 0.925], quaternion: [1.000, 0.000, 0.000, 0.000]} #to be updated
  # - {name: "approach_pick_object_tower_1",   frame: "world", position: [-0.061, -0.668, 1.200], quaternion: [1.000, 0.000, 0.000, 0.000]} #to be updated
  #
  # - {name: "pick_object_tower_2",            frame: "world", position: [-0.020, -0.668, 0.925], quaternion: [1.000, 0.000, 0.000, 0.000]} #to be updated
  # - {name: "approach_pick_object_tower_2",   frame: "world", position: [-0.020, -0.668, 1.200], quaternion: [1.000, 0.000, 0.000, 0.000]} #to be updated

  #
  # - {name: "guide0",      frame: "table", position: [0.300, 0.400, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide1",      frame: "table", position: [0.300, 0.600, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide2",      frame: "table", position: [0.300, 0.800, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide3",      frame: "table", position: [0.300, 1.000, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide4",      frame: "table", position: [0.300, 1.200, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide5",      frame: "table", position: [0.300, 1.400, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide6",      frame: "table", position: [0.300, 1.600, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide0_down", frame: "table", position: [0.300, 0.400, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide1_down", frame: "table", position: [0.300, 0.600, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide2_down", frame: "table", position: [0.300, 0.800, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide3_down", frame: "table", position: [0.300, 1.000, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide4_down", frame: "table", position: [0.300, 1.200, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide5_down", frame: "table", position: [0.300, 1.400, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "guide6_down", frame: "table", position: [0.300, 1.600, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  #
  # - {name: "internal0",      frame: "table", position: [-0.300, 0.400, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal1",      frame: "table", position: [-0.300, 0.600, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal2",      frame: "table", position: [-0.300, 0.800, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal3",      frame: "table", position: [-0.300, 1.000, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal4",      frame: "table", position: [-0.300, 1.200, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal5",      frame: "table", position: [-0.300, 1.400, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal6",      frame: "table", position: [-0.300, 1.600, 0.300], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal0_down", frame: "table", position: [-0.300, 0.400, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal1_down", frame: "table", position: [-0.300, 0.600, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal2_down", frame: "table", position: [-0.300, 0.800, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal3_down", frame: "table", position: [-0.300, 1.000, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal4_down", frame: "table", position: [-0.300, 1.200, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal5_down", frame: "table", position: [-0.300, 1.400, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}
  # - {name: "internal6_down", frame: "table", position: [-0.300, 1.600, 0.200], quaternion: [0.70717, 0.70717, 0.0, 0.0]}

go_to_location_server:

  ik_sol_number: 16
  max_stall_iter: 160000
  collision_detector: FCL

  groups:
    manipulator: open_tip





  manipulator:
    preferred_configuration: [1.5707963267949, -2.44346095279206, 2.44346095279206,-1.5707963267949, 1.5707963267949, 0]


    preferred_configuration_weight: [1, 1, 1, 1, 1, 1]
    max_ik_goal_number: 32
    use_single_goal: false
    upper_bound: [ 3.14159265358979, -0.122173, 2.75,  3.14,  3.14,  3.14]
    lower_bound: [-3.14159265358979, -3.05,    -2.75, -3.14, -3.14, -3.14]


  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints
