# inbound:
#   boxes:
#  - {name: "sp1",            frame: "table",        position: [ 0.004, 1.005, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.05] } # vettore
#  - {name: "sp2",            frame: "table",        position: [ 0.004, 1.078, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.05] } # vettore
#  - {name: "sp3",            frame: "table",        position: [ 0.004, 1.136, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.05] } # vettore
#  - {name: "sp4",            frame: "table",        position: [ 0.004, 1.208, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.05] } # vettore
#  - {name: "sp5",            frame: "table",        position: [ 0.004, 1.268, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.05] } # vettore
#  - {name: "sg1",            frame: "table",        position: [ 0.045, 0.529, 0.054], quaternion: [0.7071068, -0.7071068, -0.000, -0.000], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.15]} # vettore
#  - {name: "sg2",            frame: "table",        position: [ 0.045, 0.673, 0.054], quaternion: [0.7071068, -0.7071068, -0.000, -0.000], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.15]} # vettore
#  - {name: "sg3",            frame: "table",        position: [ 0.045, 0.803, 0.054], quaternion: [0.7071068, -0.7071068, -0.000, -0.000], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.15]} # vettore
#  - {name: "sg4",            frame: "table",        position: [ 0.045, 0.930, 0.054], quaternion: [0.7071068, -0.7071068, -0.000, -0.000], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.15]} # vettore
  # - {name: "piece_area",     frame: "table",       position: [ 0.004, 1.005, 0.053],  quaternion: [1.000, 0.000, 0.000, 0.000], approach_distance: [0, 0, -0.15], leave_distance: [0, 0, -0.15] } # vettore

inbound_pick_server:

  ik_sol_number: 4
  max_stall_iter: 100
  collision_detector: FCL

  groups:
    manipulator: open_tip

  manipulator:
    preferred_configuration: [1.5707963267949, -2.44346095279206, 2.44346095279206,-1.5707963267949, 1.5707963267949, 0]
    preferred_configuration_weight: [1, 1, 1, 1, 1, 1]
    max_ik_goal_number: 32
    use_single_goal: false
    upper_bound: [ 3.14159265358979, -0.122173, 2.75,  3.14,  3.14,  3.14]
    lower_bound: [-3.14159265358979, -3.05,    -2.75, -3.14, -3.14, -3.14]

  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints
