subjobs_list:
  touch_z:        {next_state_if_success: "touch_z_refine", next_state_if_fail: "FAIL", type: "Touch",   goal_twist: [0,0,-0.001,0,0,0],  goal_twist_frame: "world", target_force: 15, relative_target: False, release_condition: "Force", release_force: 5}
  touch_z_refine: {next_state_if_success: "SUCCESS",        next_state_if_fail: "FAIL", type: "Touch",   goal_twist: [0,0,-0.0005,0,0,0], goal_twist_frame: "world", target_force: 10, relative_target: False, release_condition: "Force", release_force: 5}
  close_gripper:  {next_state_if_success: "SUCCESS",        next_state_if_fail: "FAIL", type: "Gripper", position: 0, force: 100, velocity: 30}
initial_state: touch_z
