subjobs_list:

  close_gripper:
    next_state_if_success: "move_down_1"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 0
    force: 100
    velocity: 100

  move_down_1:
    next_state_if_success: "push_x"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: -62
    linear_velocity_mm_s: 20
  # spingo per avere il riscontro
  push_x:
      next_state_if_success: "move_up_1"
      next_state_if_fail: "FAIL"
      type: Touch
      goal_twist: [0.001,0,0,0,0,0]
      goal_twist_frame: "world"
      target_force: 10
      relative_target: False
      release_condition: "Position"
      release_position: 0.005

  move_up_1:
    next_state_if_success: "move_x_1"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: 46
    linear_velocity_mm_s: 20



  move_x_1:
    next_state_if_success: "push_z"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traXmm: 40
    linear_velocity_mm_s: 20



  push_z:
      next_state_if_success: "move_y_1"
      next_state_if_fail: "FAIL"
      type: Touch
      goal_twist: [0,0,-0.001,0,0,0]
      goal_twist_frame: "world"
      target_force: 3
      relative_target: True
      release_condition: "Position"
      release_position: 0.005


  move_y_1:
    next_state_if_success: "move_x_2"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traYmm: -41
    linear_velocity_mm_s: 20


  move_x_2:
    next_state_if_success: "move_down_2"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traXmm: 76.3
    linear_velocity_mm_s: 20



  move_down_2:
    next_state_if_success: "push_y"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: -42
    linear_velocity_mm_s: 20



  push_y:
      next_state_if_success: "gripper_20"
      next_state_if_fail: "FAIL"
      type: Touch
      goal_twist: [0,0.001,0,0,0,0]
      goal_twist_frame: "world"
      target_force: 50
      relative_target: False
      release_condition: "Position"
      release_position: 0.000


  gripper_20:
    next_state_if_success: "move_up"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 20
    force: 100
    velocity: 100

  move_up:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: 60
    linear_velocity_mm_s: 20

initial_state: close_gripper
