object_geometries:
  pieceA:
    color: [1,0.8,0,1.]
    box:  [0.03,0.03,0.01]

    offset: [0.069,-0.012,-0.005] #

  mounting_plateA:
    color: [0.2,0.2,0.2,1.0]
    box:  [0.180,0.270,0.150]
    offset: [0.0,0.0,-0.075] #

  mounting_plateA_upper_part:
    color: [0.2,0.2,0.2,1.0]
    box:  [0.110,0.075,0.046]
    offset: [0.0,0.0,-0.023] #

  mounting_plateA_slide:
    color: [0.2,0.2,0.2,1.0]
    box:  [0.08,0.150,0.030]
    offset: [0.0,0.0,-0.015] #

  blank_piece_location:
    color: [1,0.8,0,1.0]
    box:  [0.03,0.03,0.01]
    offset: [0.0,0.0,0.005]

  squadra_piccola:
    # color: [0.2,0.2,0.2, 1.]
    box:  [0.019,0.03,0.012]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  pin:
    # color: [0.2,0.2,0.2, 0.4]
    box:  [0.02,0.02,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  squadra_grande:
    # color: [0.2,0.2,0.2, 1.]
    box:  [0.03,0.01,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  cube:
    color: [1, 1, 1, 1]
    box:  [0.05,0.05,0.05]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.03]

  little_cube:
    box:  [0.015,0.015,0.015]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  plate:
    box: [0.17,0.01,0.025]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  L_plate:
    box: [0.16,0.03,0.03]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  green_cube:
    color: [0, 1, 0, 1]
    box:  [0.05,0.05,0.05]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  light_blue_cube:
    color: [0.5294, 0.8078, 0.9804, 1]
    box:  [0.05,0.05,0.05]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  pink_cube:
    color: [1, 0.7529, 0.7961, 1]
    box:  [0.05,0.05,0.05]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  white_cube:
    color: [1, 1, 1, 1]
    box:  [0.05,0.05,0.05]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  yellow_cube:
    color: [1, 1, 0, 1]
    box:  [0.05,0.05,0.05]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  deo:
    color: [1, 1, 0, 1]
    box:  [0.045,0.045,0.095]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.052]

  outbound_box:
    color: [1, 1, 0, 1]
    box:  [0.30,0.20,0.12]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, -0.06]

  cylinder:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]



  colonna:
    color:  [1.00,1.00,1.0,1.0]
    box:    [0.50,0.02,0.70]
    offset: [0.00,0.00,0.35] #
  tetto:
    color:  [1.00,1.00,1.0,1.0]
    box:    [0.50,0.73,0.020]
    offset: [0.00,0.00,0.010] #


  obstacle_prove_cembre:
    color: [1.0,1.0,1.0,1.0]
    box:  [0.50,0.73,0.70]
    offset: [0.0,0.0,0.35] #

  cylinder_cembre_small:
    color: [1, 1, 0, 1]
    box:  [0.045,0.045,0.021]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.0135]

  cylinder_cembre_big:
    color: [1, 1, 0, 1]
    box:  [0.055,0.055,0.035]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.0205]
