object_geometries:
  pieceA:
    color: [1,0.8,0,1.]
    box:  [0.07,0.08,0.01]

    offset: [0,0,-0.005] #
    grasp_poses:
    - {tool: "open_tip", position: [0, 0, 0.010], quaternion: [0,0,0,1]}
    - {tool: "open_tip", position: [0, 0, 0.010], quaternion: [0,0,1,0]}
    - {tool: "open_tip", position: [0, 0, 0.010], quaternion: [ 0, 0, 0.7071068, 0.7071068 ]}
    - {tool: "open_tip", position: [0, 0, 0.010], quaternion: [ 0, 0, -0.7071068, 0.7071068 ]}

  mounting_plateA:
    color: [0.2,0.2,0.2,1.0]
    box:  [0.180,0.270,0.150]
    offset: [0.0,0.0,-0.075] #

  mounting_plateA_upper_part:
    color: [0.2,0.2,0.2,1.0]
    box:  [0.110,0.075,0.046]
    offset: [0.0,0.0,-0.023] #

  mounting_plateA_slide:
    color: [0.2,0.2,0.2,1.0]
    box:  [0.08,0.150,0.030]
    offset: [0.0,0.0,-0.015] #
