scene_objects:
# - {type: "mounting_plateA", frame: "table", position: [ 0.300, 0.500, 0.160], quaternion: [0,0,0,1]}
# - {type: "mounting_plateA_upper_part", frame: "table", position: [ 0.300, 0.5175, 0.206], quaternion: [0,0,0,1]}
# - {type: "mounting_plateA_slide", frame: "table", position: [ 0.300, 0.555, 0.206], quaternion: [0,0,0,1]}
 # - {type: "obstacle_prove_cembre", frame: "table", position: [ 0.3, 1.0,  0.10], quaternion: [0.0, 0.0, 0.0, 1.0]}
 - {type: "table_top",   frame: "table", position: [  0.350, 1.43,  0.70], quaternion: [0.0, 0.0, 0.0, 1.0]}
 - {type: "table_leg",   frame: "table", position: [  0.115, 1.08,  0.0],  quaternion: [0.0, 0.0, 0.0, 1.0]}
 - {type: "table_leg",   frame: "table", position: [  0.584, 1.78,  0.0],  quaternion: [0.0, 0.0, 0.0, 1.0]}
 - {type: "table_leg",   frame: "table", position: [  0.584, 1.08,  0.0],  quaternion: [0.0, 0.0, 0.0, 1.0]}
 - {type: "table_leg",   frame: "table", position: [  0.115, 1.78,  0.0],  quaternion: [0.0, 0.0, 0.0, 1.0]}
 - {type: "inbound_box", frame: "table", position: [  0.33,  1.50,  0.0],  quaternion: [0.0, 0.0, 0.0, 1.0]}
