scene_objects:
# - {type: "obstacle_prove_cembre", frame: "table", position: [ 0.45, 1.0,  0.10], quaternion: [0.0, 0.0, 0.0, 1.0]}
 - {type: "colonna", frame: "table", position: [ 0.35, 0.65,  0.00], quaternion: [0.0, 0.0, 0.0, 1.0]}
 - {type: "colonna", frame: "table", position: [ 0.35, 1.35,  0.00], quaternion: [0.0, 0.0, 0.0, 1.0]}
 - {type: "tetto",   frame: "table", position: [ 0.35, 1.0,   0.70], quaternion: [0.0, 0.0, 0.0, 1.0]}
