outbound:
  slots_group:
  - {name: "group_A"}
  - {name: "group_B"}
  - {name: "equipment"}

outbound_place_server:

  ik_sol_number: 16
  max_stall_iter: 16000
  collision_detector: FCL

  groups:
    manipulator: open_tip

  manipulator:
    preferred_configuration: [1.5707963267949, -2.44346095279206, 2.44346095279206,-1.5707963267949, 1.5707963267949, 0]

    preferred_configuration_weight: [0, 1, 1, 1, 1, 1]
    max_ik_goal_number: 32
    use_single_goal: false
    upper_bound: [ 2.6, -0.087266462599717, 2.6,  3.14,  3.14,  3.14]
    lower_bound: [-2.6, -2.26892802759263, -2.0, -3.14, -3.14, -3.14]


  request_adapters:
  - default_planner_request_adapters/AddTimeParameterization
  - default_planner_request_adapters/FixWorkspaceBounds
  - default_planner_request_adapters/FixStartStateBounds
  - default_planner_request_adapters/FixStartStateCollision
  - default_planner_request_adapters/FixStartStatePathConstraints
