scene_objects:
#- {type: "pieceA", frame: "Marker1", position: [ 0.071, -0.14, 0.0], quaternion: [0,0,0,1]}
- {type: "pieceA", frame: "table", position: [-0.212, 1.364, 0.063], quaternion: [0.000, 0.026, 0.716, 0.698]}
