multi_skills:
  group_name: "manipulator"
  recipe:
  - {action: "goto",  description: ["remove_staffa_pezzo_cilindrico"],  property_exec_id: "remove_staffa_cilindro", to_loc_ctrl_id: "trajectory_tracking", job_exec_name: "/ssm_job/exec", tool_id: ""}
  - {action: "goto",  description: ["presa_staffa_up_tmp"],  property_exec_id: "", to_loc_ctrl_id: "trajectory_tracking", job_exec_name: "/ssm_job/exec", tool_id: ""}
  - {action: "goto",  description: ["presa_staffa"],  property_exec_id: "open", job_exec_name: "/robotiq_gripper", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
  - {action: "goto",  description: ["presa_staffa_up_tmp"],  property_exec_id: "", to_loc_ctrl_id: "trajectory_tracking", job_exec_name: "/ssm_job/exec", tool_id: ""}
  - {action: "goto",  description: ["pezzo_cilindrico"],  property_exec_id: "remove_cilindro", to_loc_ctrl_id: "trajectory_tracking", job_exec_name: "/ssm_job/exec", tool_id: ""}
  - {action: "goto",  description: ["lavorato_inbound_up_tmp"],  property_exec_id: "", to_loc_ctrl_id: "trajectory_tracking", job_exec_name: "/ssm_job/exec", tool_id: ""}
  - {action: "goto",  description: ["lavorato_inbound"],  property_exec_id: "open", job_exec_name: "/robotiq_gripper", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
  - {action: "goto",  description: ["lavorato_inbound_up_tmp"],  property_exec_id: "", to_loc_ctrl_id: "trajectory_tracking", job_exec_name: "/ssm_job/exec", tool_id: ""}


# "pezzo_cilindrico",
# "remove_staffa_pezzo_cilindrico
# "insert_staffa_pezzo_cilindrico
# "presa_staffa",
# "presa_staffa_up_tmp
# "cilindro_inbound",
# "cilindro_inbound_up_tmp
# "lavorato_inbound",
# "lavorato_inbound_up_tmp
