multi_skills:
  group_name: "manipulator"
  recipe:
  - {action: "goto",  description: ["cilindro_inbound_up_tmp"],  property_exec_id: "", job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
  - {action: "goto",  description: ["cilindro_inbound"],  property_exec_id: "pos_0_force_100_vel_50", job_exec_name: "/robotiq_gripper", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
  - {action: "goto",  description: ["cilindro_inbound_up_tmp"],  property_exec_id: "", job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
  - {action: "goto",  description: ["pezzo_cilindrico"],  property_exec_id: "insert_cilindro", job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
  - {action: "goto",  description: ["presa_staffa_up_tmp"],  property_exec_id: "", job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
  - {action: "goto",  description: ["presa_staffa"],  property_exec_id: "pos_0_force_100_vel_50", job_exec_name: "/robotiq_gripper", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
  - {action: "goto",  description: ["presa_staffa_up_tmp"],  property_exec_id: "", job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
  - {action: "goto",  description: ["insert_staffa_pezzo_cilindrico"],  property_exec_id: "insert_staffa_cilindro", job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}


# "pezzo_cilindrico",
# "remove_staffa_pezzo_cilindrico
# "
# "presa_staffa",
# "presa_staffa_up_tmp
# "cilindro_inbound",
# "cilindro_inbound_up_tmp
# "lavorato_inbound",
# "lavorato_inbound_up_tmp
