subjobs_list:
  gripper_50:
    next_state_if_success: "move_down"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 50
    force: 100
    velocity: 100
  move_down:
    next_state_if_success: "push_z"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: -90
    linear_velocity_mm_s: 20
  push_z:
    next_state_if_success: "close_gripper"
    next_state_if_fail: "FAIL"
    type: Touch
    goal_twist: [0,0,-0.001,0,0,0]
    goal_twist_frame: "world"
    target_force: 7
    relative_target: True
    release_condition: "Position"
    release_position: 0.001
  close_gripper:
    next_state_if_success: "move_up"
    next_state_if_fail: "FAIL"
    type: Gripper
    position: 0
    force: 100
    velocity: 100
  move_up:
    next_state_if_success: "SUCCESS"
    next_state_if_fail: "FAIL"
    type: RelativeMove
    frame: table
    traZmm: 90
    linear_velocity_mm_s: 20

initial_state: gripper_50
