scene_objects:
# - {type: "box_grigio", frame: "table", position: [0.63, 0.956, 0.125], quaternion: [0, 0, 0, 1]}
# - {type: "box_grigio", frame: "table", position: [0.63, 0.400, 0.125], quaternion: [0, 0, 0, 1]}
# - {type: "blank_piece_location", frame: "table", position: [0.05, 1.0, 0.0], quaternion: [0, 0, 0, 1]}
- {type: "cube", frame: "table", position: [ 0.15, 1.0, 0.2], quaternion: [0,0,0,1]}
# - {type: "pin", frame: "table", position: [0.63, 2.400, 0.125], quaternion: [0, 0, 0, 1]}
#
# box_grigio:
#   color: [0.2,0.2,0.2, 1.]
#   box:  [0.19,0.30,0.12]
#   offset_quaternion: [ 0, 0, 0, 1 ]
#   offset: [0, 0, -0.06]
#
#
# barra_testa:
#   color: [0.2,0.2,0.2, 0.4]
#   box:  [0.2,2.0,0.6]
#   offset_quaternion: [ 0, 0, 0, 1 ]
#   offset: [0, 0, 0]
