scene_objects:
# - {type: "mounting_plateA", frame: "table", position: [ 0.300, 0.500, 0.160], quaternion: [0,0,0,1]}
# - {type: "mounting_plateA_upper_part", frame: "table", position: [ 0.300, 0.5175, 0.206], quaternion: [0,0,0,1]}
# - {type: "mounting_plateA_slide", frame: "table", position: [ 0.300, 0.555, 0.206], quaternion: [0,0,0,1]}
 - {type: "outbound_box", frame: "table", position: [ 0.3, 0.30, 0.105], quaternion: [0.703, 0.711, 0.015, 0.016]}
 - {type: "outbound_box", frame: "table", position: [ -0.34, 1.70, 0.015], quaternion: [0.703, 0.711, 0.015, 0.016]}
