scene_objects:
- {type: "cylinder", frame: "table", position: [0.54,  0.395, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.54,  0.54, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.54,  0.70, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.54,  0.845, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.54,  1.0, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.54,  1.15, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.54,  1.30, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.54,  1.45, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.54,  1.60, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.06,  0.39, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.06,  0.55, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.06,  0.70, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.06,  0.85, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.06,  0.995, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.06,  1.15, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.06,  1.295, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.06,  1.465, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.06,  1.62, 0.0], quaternion: [0,0,0,1]}
- {type: "cylinder", frame: "table", position: [0.06,  1.82, 0.0], quaternion: [0,0,0,1]}
