scene_objects:
#- {type: "barra_testa", frame: "table", position: [0.80, 1.0, 0.9], quaternion: [0, 0, 0, 1]}
- {type: "box_grigio", frame: "table", position: [0.63, 0.956, 0.225], quaternion: [0, 0, 0, 1]}
- {type: "blank_piece_location",  frame: "table", position: [ 0.005, 1.005, 0.07], quaternion: [0,0,0,1]}
- {type: "cube", frame: "table", position: [0.005, 0.805, 0.07], quaternion: [0, 0, 0, 1]}
- {type: "squadra_piccola", frame: "table", position: [0.005, 1.205, 0.07], quaternion: [0, 0, 0, 1]}
- {type: "squadra_grande", frame: "table", position: [0.005, 1.305, 0.07], quaternion: [0, 0, 0, 1]}
# - {type: "bin", frame: "table", position: [0.63, 0.700, 0.225], quaternion: [0, 0, 0, 1]}

box_grigio:
  color: [0.2,0.2,0.2, 1.]
  box:  [0.19,0.30,0.12]
  offset_quaternion: [ 0, 0, 0, 1 ]
  offset: [0, 0, -0.06]


barra_testa:
  color: [0.2,0.2,0.2, 0.4]
  box:  [0.2,2.0,0.6]
  offset_quaternion: [ 0, 0, 0, 1 ]
  offset: [0, 0, 0]
