scene_objects:
# - {type: "mounting_plateA", frame: "table", position: [ 0.300, 0.500, 0.160], quaternion: [0,0,0,1]}
# - {type: "mounting_plateA_upper_part", frame: "table", position: [ 0.300, 0.5175, 0.206], quaternion: [0,0,0,1]}
# - {type: "mounting_plateA_slide", frame: "table", position: [ 0.300, 0.555, 0.206], quaternion: [0,0,0,1]}
 # - {type: "obstacle_prove_cembre", frame: "table", position: [ 0.3, 1.0,  0.10], quaternion: [0.0, 0.0, 0.0, 1.0]}
 - {type: "table_top",   frame: "table", position: [  0.30, 1.12,  0.75], quaternion: [0.7071068, 0, 0, 0.7071068 ]}
 - {type: "table_leg",   frame: "table", position: [  0.05, 1.11,  0.4],  quaternion: [0.0, 0.7071068,  0, 0.7071068]}
 - {type: "inbound_box", frame: "table", position: [  0.33,  1.50,  0.0],  quaternion: [0.0, 0.0, 0.0, 1.0]}
