go_to_location:
- {name: "Test01", frame: "table", position: [0.3, 0.70, 0.25], quaternion: [1,0,0,0]}
- {name: "Test02", frame: "table", position: [0.3, 0.75, 0.25], quaternion: [1,0,0,0]}
- {name: "Test02", frame: "table", position: [0.3, 0.80, 0.25], quaternion: [1,0,0,0]}
- {name: "Test03", frame: "table", position: [0.3, 0.85, 0.25], quaternion: [1,0,0,0]}
- {name: "Test04", frame: "table", position: [0.3, 0.90, 0.25], quaternion: [1,0,0,0]}
- {name: "Test03", frame: "table", position: [0.3, 1.00, 0.25], quaternion: [1,0,0,0]}
- {name: "Test05", frame: "table", position: [0.3, 1.05, 0.25], quaternion: [1,0,0,0]}
- {name: "Test03", frame: "table", position: [0.3, 1.10, 0.25], quaternion: [1,0,0,0]}
- {name: "Test06", frame: "table", position: [0.3, 1.10, 0.25], quaternion: [1,0,0,0]}
- {name: "Test07", frame: "table", position: [0.3, 1.15, 0.25], quaternion: [1,0,0,0]}
- {name: "Test03", frame: "table", position: [0.3, 1.20, 0.25], quaternion: [1,0,0,0]}
- {name: "Test08", frame: "table", position: [0.3, 1.25, 0.25], quaternion: [1,0,0,0]}
- {name: "Test09", frame: "table", position: [0.3, 1.30, 0.25], quaternion: [1,0,0,0]}
- {name: "Test03", frame: "table", position: [0.3, 1.35, 0.25], quaternion: [1,0,0,0]}
- {name: "Test10", frame: "table", position: [0.3, 1.40, 0.25], quaternion: [1,0,0,0]}
- {name: "Test11", frame: "table", position: [0.3, 1.45, 0.25], quaternion: [1,0,0,0]}
- {name: "Test03", frame: "table", position: [0.3, 1.50, 0.25], quaternion: [1,0,0,0]}
- {name: "Test12", frame: "table", position: [0.3, 1.55, 0.25], quaternion: [1,0,0,0]}
- {name: "Test13", frame: "table", position: [0.3, 1.60, 0.25], quaternion: [1,0,0,0]}
- {name: "Test14", frame: "table", position: [0.3, 1.65, 0.25], quaternion: [1,0,0,0]}
#
- {name: "Test101", frame: "table", position: [0.4, 0.70, 0.25], quaternion: [1,0,0,0]}
- {name: "Test102", frame: "table", position: [0.4, 0.75, 0.25], quaternion: [1,0,0,0]}
- {name: "Test102", frame: "table", position: [0.4, 0.80, 0.25], quaternion: [1,0,0,0]}
- {name: "Test103", frame: "table", position: [0.4, 0.85, 0.25], quaternion: [1,0,0,0]}
- {name: "Test104", frame: "table", position: [0.4, 0.90, 0.25], quaternion: [1,0,0,0]}
- {name: "Test103", frame: "table", position: [0.4, 1.00, 0.25], quaternion: [1,0,0,0]}
- {name: "Test105", frame: "table", position: [0.4, 1.05, 0.25], quaternion: [1,0,0,0]}
- {name: "Test103", frame: "table", position: [0.4, 1.10, 0.25], quaternion: [1,0,0,0]}
- {name: "Test106", frame: "table", position: [0.4, 1.10, 0.25], quaternion: [1,0,0,0]}
- {name: "Test107", frame: "table", position: [0.4, 1.15, 0.25], quaternion: [1,0,0,0]}
- {name: "Test103", frame: "table", position: [0.4, 1.20, 0.25], quaternion: [1,0,0,0]}
- {name: "Test108", frame: "table", position: [0.4, 1.25, 0.25], quaternion: [1,0,0,0]}
- {name: "Test109", frame: "table", position: [0.4, 1.30, 0.25], quaternion: [1,0,0,0]}
- {name: "Test103", frame: "table", position: [0.4, 1.35, 0.25], quaternion: [1,0,0,0]}
- {name: "Test110", frame: "table", position: [0.4, 1.40, 0.25], quaternion: [1,0,0,0]}
- {name: "Test111", frame: "table", position: [0.4, 1.45, 0.25], quaternion: [1,0,0,0]}
- {name: "Test103", frame: "table", position: [0.4, 1.50, 0.25], quaternion: [1,0,0,0]}
- {name: "Test112", frame: "table", position: [0.4, 1.55, 0.25], quaternion: [1,0,0,0]}
- {name: "Test113", frame: "table", position: [0.4, 1.60, 0.25], quaternion: [1,0,0,0]}
- {name: "Test114", frame: "table", position: [0.4, 1.65, 0.25], quaternion: [1,0,0,0]}
#
- {name: "Test201", frame: "table", position: [0.2, 0.70, 0.25], quaternion: [1,0,0,0]}
- {name: "Test202", frame: "table", position: [0.2, 0.75, 0.25], quaternion: [1,0,0,0]}
- {name: "Test202", frame: "table", position: [0.2, 0.80, 0.25], quaternion: [1,0,0,0]}
- {name: "Test203", frame: "table", position: [0.2, 0.85, 0.25], quaternion: [1,0,0,0]}
- {name: "Test204", frame: "table", position: [0.2, 0.90, 0.25], quaternion: [1,0,0,0]}
- {name: "Test203", frame: "table", position: [0.2, 1.00, 0.25], quaternion: [1,0,0,0]}
- {name: "Test205", frame: "table", position: [0.2, 1.05, 0.25], quaternion: [1,0,0,0]}
- {name: "Test203", frame: "table", position: [0.2, 1.10, 0.25], quaternion: [1,0,0,0]}
- {name: "Test206", frame: "table", position: [0.2, 1.10, 0.25], quaternion: [1,0,0,0]}
- {name: "Test207", frame: "table", position: [0.2, 1.15, 0.25], quaternion: [1,0,0,0]}
- {name: "Test203", frame: "table", position: [0.2, 1.20, 0.25], quaternion: [1,0,0,0]}
- {name: "Test208", frame: "table", position: [0.2, 1.25, 0.25], quaternion: [1,0,0,0]}
- {name: "Test209", frame: "table", position: [0.2, 1.30, 0.25], quaternion: [1,0,0,0]}
- {name: "Test203", frame: "table", position: [0.2, 1.35, 0.25], quaternion: [1,0,0,0]}
- {name: "Test210", frame: "table", position: [0.2, 1.40, 0.25], quaternion: [1,0,0,0]}
- {name: "Test211", frame: "table", position: [0.2, 1.45, 0.25], quaternion: [1,0,0,0]}
- {name: "Test203", frame: "table", position: [0.2, 1.50, 0.25], quaternion: [1,0,0,0]}
- {name: "Test212", frame: "table", position: [0.2, 1.55, 0.25], quaternion: [1,0,0,0]}
- {name: "Test213", frame: "table", position: [0.2, 1.60, 0.25], quaternion: [1,0,0,0]}
- {name: "Test214", frame: "table", position: [0.2, 1.65, 0.25], quaternion: [1,0,0,0]}
#
- {name: "Test301", frame: "table", position: [0.3, 0.70, 0.30], quaternion: [1,0,0,0]}
- {name: "Test302", frame: "table", position: [0.3, 0.75, 0.30], quaternion: [1,0,0,0]}
- {name: "Test302", frame: "table", position: [0.3, 0.80, 0.30], quaternion: [1,0,0,0]}
- {name: "Test303", frame: "table", position: [0.3, 0.85, 0.30], quaternion: [1,0,0,0]}
- {name: "Test304", frame: "table", position: [0.3, 0.90, 0.30], quaternion: [1,0,0,0]}
- {name: "Test303", frame: "table", position: [0.3, 1.00, 0.30], quaternion: [1,0,0,0]}
- {name: "Test305", frame: "table", position: [0.3, 1.05, 0.30], quaternion: [1,0,0,0]}
- {name: "Test303", frame: "table", position: [0.3, 1.10, 0.30], quaternion: [1,0,0,0]}
- {name: "Test306", frame: "table", position: [0.3, 1.10, 0.30], quaternion: [1,0,0,0]}
- {name: "Test307", frame: "table", position: [0.3, 1.15, 0.30], quaternion: [1,0,0,0]}
- {name: "Test303", frame: "table", position: [0.3, 1.20, 0.30], quaternion: [1,0,0,0]}
- {name: "Test308", frame: "table", position: [0.3, 1.25, 0.30], quaternion: [1,0,0,0]}
- {name: "Test309", frame: "table", position: [0.3, 1.30, 0.30], quaternion: [1,0,0,0]}
- {name: "Test303", frame: "table", position: [0.3, 1.35, 0.30], quaternion: [1,0,0,0]}
- {name: "Test310", frame: "table", position: [0.3, 1.40, 0.30], quaternion: [1,0,0,0]}
- {name: "Test311", frame: "table", position: [0.3, 1.45, 0.30], quaternion: [1,0,0,0]}
- {name: "Test303", frame: "table", position: [0.3, 1.50, 0.30], quaternion: [1,0,0,0]}
- {name: "Test312", frame: "table", position: [0.3, 1.55, 0.30], quaternion: [1,0,0,0]}
- {name: "Test313", frame: "table", position: [0.3, 1.60, 0.30], quaternion: [1,0,0,0]}
- {name: "Test314", frame: "table", position: [0.3, 1.65, 0.30], quaternion: [1,0,0,0]}
