go_to_location:
- {name: "Test01", frame: "table", position: [0.3, 0.70, 0.25], quaternion: [1,0,0,0]}
- {name: "Test02", frame: "table", position: [0.3, 0.80, 0.25], quaternion: [1,0,0,0]}
- {name: "Test03", frame: "table", position: [0.3, 0.90, 0.25], quaternion: [1,0,0,0]}
- {name: "Test04", frame: "table", position: [0.3, 1.00, 0.25], quaternion: [1,0,0,0]}
- {name: "Test05", frame: "table", position: [0.3, 1.10, 0.25], quaternion: [1,0,0,0]}
- {name: "Test06", frame: "table", position: [0.3, 1.00, 0.25], quaternion: [1,0,0,0]}
- {name: "Test07", frame: "table", position: [0.3, 1.10, 0.25], quaternion: [1,0,0,0]}
- {name: "Test08", frame: "table", position: [0.3, 1.20, 0.25], quaternion: [1,0,0,0]}
- {name: "Test09", frame: "table", position: [0.3, 1.30, 0.25], quaternion: [1,0,0,0]}
- {name: "Test10", frame: "table", position: [0.3, 1.34, 0.25], quaternion: [1,0,0,0]}
