inbound:
  boxes:
  - {name: "Storage0_A1652",                  frame: "table", position: [-0.255, 0.492, 0.17], quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.05]}
  - {name: "Storage1_A1653",                  frame: "table", position: [-0.255, 0.621, 0.17], quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.05]}
  - {name: "Storage2_A1610",                  frame: "table", position: [-0.255, 0.846, 0.17], quaternion: [1.0, 0.0, 0.0, 0.0], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.05]}
