inbound:
  boxes:
  - {name: "Storage0_A1652",                  frame: "storage_box", position: [-0.144, -0.334, 0.117], quaternion: [-0.025, 0.016, 0.995, 0.100], approach_distance: [0, 0, -0.05], leave_distance: [0, 0, -0.005]}
  - {name: "Storage1_A1610",                  frame: "storage_box", position: [-0.091, -0.132, 0.008], quaternion: [-0.039, -0.014, 0.624, 0.781], approach_distance: [0, 0, -0.0], leave_distance: [0, 0, -0.00]}
  - {name: "Storage2_A1653",                  frame: "storage_box", position: [0.0, 0.0, 0.0], quaternion: [0.0, 0.0, 0.0, 1.0], approach_distance: [0, 0, -0.00], leave_distance: [0, 0, -0.000]}
