inbound:
  objects:
   - {type: "A1652",  frame: "storage_box",   position: [0.288, 0.1201, -0.041], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "storage_box",   position: [0.249, 0.1201, -0.041], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "storage_box",   position: [0.211, 0.1201, -0.041], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "storage_box",   position: [0.172, 0.1201, -0.041], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "storage_box",   position: [0.134, 0.1201, -0.041], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "storage_box",   position: [0.095, 0.1201, -0.041], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}

   - {type: "A1653",  frame: "storage_box",   position: [0.267, 0.464, -0.047], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage2_A1653"}
   - {type: "A1653",  frame: "storage_box",   position: [0.116, 0.464, -0.048], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage2_A1653"} #-200Ztool

   - {type: "A1610",  frame: "storage_box",   position: [0.104, 0.321, -0.050], quaternion: [0.7071, 0.7071, 0.0, 0.0], inbound: "Storage1_A1610"}
   - {type: "A1610",  frame: "storage_box",   position: [0.185, 0.321, -0.050], quaternion: [0.7071, 0.7071, 0.0, 0.0], inbound: "Storage1_A1610"}
   - {type: "A1610",  frame: "storage_box",   position: [0.265, 0.321, -0.049], quaternion: [0.7071, 0.7071, 0.0, 0.0], inbound: "Storage1_A1610"}
