object_geometries:

  head_protection:
    color: [0.2,0.2,0.2, 0.4]
    box:  [0.2,2.0,0.6]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  back_protection:
    color: [0.2,0.2,0.2, 0.4]
    box:  [1.0,2.0,0.2]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0.0, 0.0, 0.0]

  blue_box:
    color: [1,1,1,0.3]
    box:  [0.5,0.7,0.12]
    offset: [0.0,0.0,0.06] #

  mounting_plateA:
    color: [0.2,0.2,0.2,1.0]
    box:  [0.180,0.270,0.150]
    offset: [0.0,0.0,-0.075] #

  mounting_plateA_upper_part:
    color: [0.2,0.2,0.2,1.0]
    box:  [0.110,0.075,0.046]
    offset: [0.0,0.0,-0.023] #

  mounting_plateA_slide:
    color: [0.2,0.2,0.2,1.0]
    box:  [0.08,0.150,0.030]
    offset: [0.0,0.0,-0.015] #

  cylinder_cembre_small:
    color: [1, 1, 0, 1]
    box:  [0.045,0.045,0.021]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.0135]

  cylinder_cembre_big:
    color: [1, 1, 0, 1]
    box:  [0.055,0.055,0.035]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.018]

  table_top:
    color: [1, 1, 0, 1]
    box:  [0.50,0.73,0.05]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.01]

  table_leg:
    color: [1, 1, 0, 1]
    box:  [0.06,0.06,0.70]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.35]

  inbound_box:
    color: [1, 1, 0, 1]
    box:  [0.18,0.18,0.24]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0.0, 0.0, 0.12]

  MountingArea_A1610:
    color: [0.2,0.2,0.2, 1.]
    box:  [0.50,0.50,0.3]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.15]

  MountingArea_A1652:
    color: [0.2,0.2,0.2, 1.]
    box:  [0.50,0.50,0.3]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.15]

  MountingArea_A1653:
    color: [0.2,0.2,0.2, 1.]
    box:  [0.50,0.50,0.3]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.15]

  A1610:
    color: [1, 1, 1, 1]
    box:  [0.080,0.070,0.009]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.2]

  A1652:
    color: [1, 1, 1, 1]
    box:  [0.008, 0.113, 0.038]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0]

  A1653:  # cilindro
    color: [1, 1, 1, 1]
    #cylinder:  [0.140,0.024]
    box:  [0.140, 0.140, 0.024]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.2]

  cylinder_1:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_2:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_3:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_4:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_5:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_6:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_7:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_8:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_9:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_10:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_11:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_12:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_13:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_14:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_15:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_16:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_17:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_18:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]

  cylinder_19:
    color: [1, 1, 0, 1]
    box:  [0.04,0.04,0.175]
    offset_quaternion: [ 0, 0, 0, 1 ]
    offset: [0, 0, 0.09]
