inbound:
  objects:
   - {type: "pin",  frame: "Warehouse_staffa_21A1122",   position: [ 0.0, 0.0, 0.0], quaternion: [0,0,0,1], inbound: "Warehouse_staffa_21A1122"}
   #- {type: "pin",  frame: "Warehouse_grezzo_21A1122",   position: [ 0.0, 0.0, 0.0], quaternion: [0,0,0,1], inbound: "Warehouse_grezzo_21A1122"}
   #- {type: "pin",  frame: "Warehouse_lavorato_21A1122", position: [ 0.0, 0.0, 0.0], quaternion: [0,0,0,1], inbound: "Warehouse_lavorato_21A1122"}
