inbound:
  objects:
   - {type: "A1652",  frame: "table",   position: [-0.353, 0.496, 0.148], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "table",   position: [-0.315, 0.496, 0.147], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "table",   position: [-0.278, 0.496, 0.146], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "table",   position: [-0.239, 0.496, 0.144], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "table",   position: [-0.200, 0.496, 0.143], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "table",   position: [-0.161, 0.496, 0.141], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}

   - {type: "A1653",  frame: "table",   position: [-0.334, 0.846, 0.144], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage2_A1653"}
   - {type: "A1653",  frame: "table",   position: [-0.182, 0.846, 0.137], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage2_A1653"}
