inbound:
  objects:
   - {type: "A1652",  frame: "table",   position: [-0.353, 0.496, 0.148], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "table",   position: [-0.315, 0.496, 0.147], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "table",   position: [-0.278, 0.496, 0.146], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "table",   position: [-0.239, 0.496, 0.144], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "table",   position: [-0.200, 0.496, 0.143], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}
   - {type: "A1652",  frame: "table",   position: [-0.161, 0.496, 0.141], quaternion: [1.0, 0.0, 0.0, 0.0], inbound: "Storage0_A1652"}

   - {type: "A1653",  frame: "table",   position: [-0.324, 0.851, 0.281], quaternion: [0.100, 0.995, -0.016, -0.025], inbound: "Storage2_A1653"}
   - {type: "A1653",  frame: "table",   position: [-0.181, 0.850, 0.275], quaternion: [0.100, 0.995, -0.010, -0.009], inbound: "Storage2_A1653"} #-200Ztool

   - {type: "A1610",  frame: "table",   position: [-0.187, 0.704, 0.273], quaternion: [0.699, 0.715, 0.009, 0.008], inbound: "Storage1_A1610"}
   - {type: "A1610",  frame: "table",   position: [-0.262, 0.703, 0.274], quaternion: [0.699, 0.715, 0.009, 0.008], inbound: "Storage1_A1610"}
   - {type: "A1610",  frame: "table",   position: [-0.346, 0.704, 0.278], quaternion: [0.699, 0.715, 0.009, 0.008], inbound: "Storage1_A1610"}
