scene_objects:
# - {type: "mounting_plateA", frame: "table", position: [ 0.300, 0.500, 0.160], quaternion: [0,0,0,1]}
# - {type: "mounting_plateA_upper_part", frame: "table", position: [ 0.300, 0.5175, 0.206], quaternion: [0,0,0,1]}
# - {type: "mounting_plateA_slide", frame: "table", position: [ 0.300, 0.555, 0.206], quaternion: [0,0,0,1]}
 - {type: "mounting_area",  frame: "table", position: [ 0.302, 0.501, 0.0], quaternion: [0,0,0,1]}
 - {type: "mounting_area",  frame: "table", position: [ 0.300, 1.501, 0.0], quaternion: [0,0,0,1]}
