manipulation_object_types:
- grasp_poses:
  - approach_distance:
    - 0.0
    - 0.0
    - -0.1
    gripper_force: 100.0
    leave_distance:
    - 0.0
    - 0.0
    - -0.1
    position:
    - 0
    - 0
    - -0.02
    quaternion:
    - 0
    - 0
    - 0
    - 1
    post_gripper_position: 0.0
    pre_gripper_position: 45.0

    tool: open_tip
  type: pin
