group_name: "manipulator"
recipe:
- {action: "pick",   description: ["cylinder_1"],  property_exec_id: "open", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "place",  description: ["P1_A1610"],  property_exec_id: "close",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "gripper_fake"}



#order of cylinders HAMP:
#left: 1 2 10 11
#right: 9 19 8 18 7
#left: 3 12 4
#right 17 6 16 15
#left: 5 13 14

#order of cylinders non-hamp:
#left: 5 4 6 13 14 15 3 2 1 10 11 12
#right: 7 8 16 9 17 18 19
