group_name: "manipulator"
recipe:
# 21A1121
- {action: "goto",   description: ["pick_A1610"],  property_exec_id: "pick_A1610",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["place_A1610"],     property_exec_id: "mount_A1610",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}

message: "Loading"
position: 1
storage: 0
