group_name: "manipulator"
recipe:
# 21A1121
- {action: "pick",  description: ["A1653"],  property_exec_id: "pick_A1653",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}

message: "Loading"
position: 1
storage: 0
