group_name: "manipulator"
recipe:
# 21A1122
- {action: "pick",   description: ["A1650"],  property_exec_id: "pick_A1650",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "place",  description: ["P1_A1650"],  property_exec_id: "mount_A1650",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
