group_name: "manipulator"
recipe:
- {action: "pick",   description: ["A1610"],  property_exec_id: "pick_A1610",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "place",  description: ["P2_A1610"],  property_exec_id: "mount_A1610",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["P2_A1610_close_ganascia"],  property_exec_id: "close_ganascia_A1610",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}

message: "Loading"
position: 2
storage: 0
