group_name: "manipulator"
recipe:
# 21A1121
- {action: "pick",  description: ["A1652"],  property_exec_id: "pick_A1652",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: ""}
