group_name: "manipulator"
recipe:
- {action: "goto",   description: ["home"],  property_exec_id: "screw_A1_A1653",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["home"],  property_exec_id: "screw_A1_A1653",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["home"],  property_exec_id: "screw_A1_A1653",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["home"],  property_exec_id: "screw_A1_A1653",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["home"],  property_exec_id: "screw_A1_A1653",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["home"],  property_exec_id: "screw_A1_A1653",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["home"],  property_exec_id: "screw_A1_A1653",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}

message: "Loading"
position: 1
storage: 0
