group_name: "manipulator"
recipe:
- {action: "goto",   description: ["unmount_P1_A1653_STAFFA"],  property_exec_id: "unmount_A1653_STAFFA",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["Storage_A1653_STAFFA_up"],     property_exec_id: "close",   job_exec_name: "/robotiq_gripper", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["Storage_A1653_STAFFA"],     property_exec_id: "open",   job_exec_name: "/robotiq_gripper", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["Storage_A1653_STAFFA_up"],     property_exec_id: "open",   job_exec_name: "/robotiq_gripper", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["unmount_P1_A1653"],         property_exec_id: "unmount_A1653",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["Storage1_UNLOAD"],          property_exec_id: "open",   job_exec_name: "/robotiq_gripper", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}

message: "Unloading"
position: 1
storage: 1
