group_name: "manipulator"
recipe:
- {action: "goto",   description: ["unmount_P1_A1652_sx"],  property_exec_id: "unmount_A1652_sx",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["Storage0_UNLOAD"],  property_exec_id: "open",   job_exec_name: "/robotiq_gripper", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["unmount_P1_A1652_dx"],  property_exec_id: "unmount_A1652_dx",   job_exec_name: "/ssm_job/exec", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}
- {action: "goto",   description: ["Storage0_UNLOAD"],  property_exec_id: "open",   job_exec_name: "/robotiq_gripper", to_loc_ctrl_id: "trajectory_tracking", tool_id: "robotiq_simplified"}

message: "Unloading"
position: 1
storage: 1
